import { stringify } from "yaml";
import type { WorkflowIR } from "@zcicd/workflow-ir";
import { validateWorkflowIR } from "./validator.js";
import { runOptimizationPasses, type CompilerContext } from "./passes/index.js";

function buildHeaderComment(ir: WorkflowIR, context?: CompilerContext): string {
  const jobNames = ir.jobs.map(j => j.name ?? j.id).join(", ");
  const isCachingEnabled = context?.options?.enableCaching !== false;
  const isHardeningEnabled = context?.options?.enableHardening !== false;

  const featureTags: string[] = ["Parallel DAG"];
  featureTags.push(`Dependency Caching: ${isCachingEnabled ? "Enabled" : "Disabled"}`);
  featureTags.push(`Production Hardening: ${isHardeningEnabled ? "Enabled" : "Disabled"}`);

  return `# ==============================================================================
# Generated by Zero-Config CI/CD Engine
# Workflow: ${jobNames || "CI"} (${ir.jobs.length} ${ir.jobs.length === 1 ? "job" : "jobs"})
# Configuration: ${featureTags.join(" | ")}
# ==============================================================================
`;
}

export function compileWorkflowYAML(
  ir: WorkflowIR,
  context?: CompilerContext
): string {
  // 1. Run Compiler Optimization Passes
  const optimizedIR = context ? runOptimizationPasses(ir, context) : ir;

  // 2. Validate Optimized IR
  const validation = validateWorkflowIR(optimizedIR);
  if (!validation.valid) {
    const errorDetails = validation.errors.map(e => `  - [${e.path}] ${e.message}`).join("\n");
    throw new Error(`WorkflowIR validation failed:\n${errorDetails}`);
  }

  // 3. Build Triggers Object
  const onObj: Record<string, unknown> = {};
  for (const trigger of optimizedIR.triggers) {
    if (trigger.event === "workflow_dispatch") {
      onObj.workflow_dispatch = {};
    } else {
      const triggerDetails: Record<string, unknown> = {};
      if (trigger.branches && trigger.branches.length > 0) {
        triggerDetails.branches = [...trigger.branches];
      }
      if (trigger.paths && trigger.paths.length > 0) {
        triggerDetails.paths = [...trigger.paths];
      }
      onObj[trigger.event] = Object.keys(triggerDetails).length > 0 ? triggerDetails : null;
    }
  }

  // 4. Build Jobs Object
  const jobsObj: Record<string, unknown> = {};
  for (const job of optimizedIR.jobs) {
    const jobDetails: Record<string, unknown> = {
      ...(job.name ? { name: job.name } : {}),
      "runs-on": job.runsOn,
      ...(job.if ? { if: job.if } : {}),
      ...(job.environment ? { environment: job.environment } : {}),
      ...(job.timeoutMinutes ? { "timeout-minutes": job.timeoutMinutes } : {}),
      ...(job.needs && job.needs.length > 0 ? { needs: job.needs } : {}),
      ...(job.strategy ? { strategy: job.strategy } : {}),
      ...(job.permissions ? { permissions: job.permissions } : {}),
      steps: job.steps.map(step => {
        if (step.kind === "uses") {
          return {
            ...(step.name ? { name: step.name } : {}),
            uses: step.uses,
            ...(step.with ? { with: step.with } : {})
          };
        }
        return {
          ...(step.name ? { name: step.name } : {}),
          run: step.run,
          ...(step.env ? { env: step.env } : {}),
          ...(step.workingDirectory ? { "working-directory": step.workingDirectory } : {})
        };
      })
    };

    jobsObj[job.id] = jobDetails;
  }

  // 5. Assemble Document Structure
  const documentObj: Record<string, unknown> = {
    name: optimizedIR.name,
    on: onObj,
    ...(optimizedIR.permissions ? { permissions: optimizedIR.permissions } : {}),
    ...(optimizedIR.concurrency ? {
      concurrency: {
        group: optimizedIR.concurrency.group,
        "cancel-in-progress": optimizedIR.concurrency.cancelInProgress
      }
    } : {}),
    jobs: jobsObj
  };

  const yamlBody = stringify(documentObj, {
    indent: 2,
    lineWidth: 0,
    simpleKeys: true,
    aliasDuplicateObjects: false
  });

  const header = buildHeaderComment(optimizedIR, context);
  return `${header}\n${yamlBody}`;
}
