import { describe, it, expect } from "vitest";
import { buildWorkflowIR } from "./builder.js";
import { validateWorkflowIR } from "./validator.js";
import { compileWorkflowYAML } from "./compiler.js";
import type { WorkflowPlan } from "@zcicd/planner";
import type { ResolvedWorkflowPlan } from "@zcicd/resolver";
import type { ProjectState } from "@zcicd/state";

describe("Phase 5 - CI Compiler Engine & Optimization Passes", () => {
  it("compiles fully optimized YAML with dependency caching, job timeouts, and concurrency cancellation", () => {
    const state: ProjectState = {
      runtime: [
        { name: "node", evidence: [{ source: "package.json", value: "node" }] },
        { name: "python", evidence: [{ source: "requirements.txt", value: "python" }] }
      ],
      packageManager: [
        { name: "pnpm", evidence: [{ source: "pnpm-lock.yaml", value: "pnpm" }] }
      ],
      frameworks: [],
      testing: [],
      tooling: [],
      infrastructure: [
        { name: "docker", evidence: [{ source: "Dockerfile", value: "docker" }] }
      ]
    };

    const plan: WorkflowPlan = {
      capabilities: [],
      matchedRules: ["node-setup", "python-test", "docker-build"],
      diagnostics: [],
      actions: [
        { id: "node-setup", type: "runtime.setup", reason: "Node", sourceRule: "node-setup" },
        { id: "python-test", type: "python.test", reason: "Python", sourceRule: "python-test" },
        { id: "docker-build", type: "docker.build", reason: "Docker", sourceRule: "docker-build" }
      ]
    };

    const resolved: ResolvedWorkflowPlan = {
      results: [],
      warnings: [],
      primitives: [
        {
          kind: "uses",
          uses: "actions/setup-node@v4",
          with: { "node-version": "20.x" },
          reason: "Node setup",
          source: "actions/starter-workflows:ci/node.js.yml",
          actionId: "node-setup"
        },
        {
          kind: "run",
          run: "pnpm test",
          reason: "Node test",
          source: "actions/starter-workflows:ci/node.js.yml",
          actionId: "node-setup"
        },
        {
          kind: "uses",
          uses: "actions/setup-python@v5",
          with: { "python-version": "3.x" },
          reason: "Python setup",
          source: "actions/starter-workflows:ci/python-app.yml",
          actionId: "python-test"
        },
        {
          kind: "run",
          run: "pytest",
          reason: "Python test",
          source: "actions/starter-workflows:ci/python-app.yml",
          actionId: "python-test"
        },
        {
          kind: "uses",
          uses: "docker/build-push-action@v6",
          with: { push: false },
          reason: "Docker build",
          source: "actions/starter-workflows:ci/docker-image.yml",
          actionId: "docker-build"
        }
      ]
    };

    const ir = buildWorkflowIR(plan, resolved);
    const yaml = compileWorkflowYAML(ir, {
      state,
      plan,
      resolved,
      options: {
        enableCaching: true,
        enableHardening: true,
        matrixVersions: {
          node: ["18.x", "20.x", "22.x"]
        }
      }
    });

    // 1. Verify Header Comment
    expect(yaml).toContain("# Generated by Zero-Config CI/CD Engine");

    // 2. Verify Concurrency Cancellation
    expect(yaml).toContain("concurrency:");
    expect(yaml).toContain("cancel-in-progress: true");

    // 3. Verify Job Timeouts
    expect(yaml).toContain("timeout-minutes: 15");

    // 4. Verify Caching Injection
    expect(yaml).toContain("cache: pnpm");
    expect(yaml).toContain("cache: pip");

    // 5. Verify Matrix Strategy
    expect(yaml).toContain("matrix:");
    expect(yaml).toContain("node-version:");
    expect(yaml).toContain("18.x");
    expect(yaml).toContain("22.x");
  });

  it("detects circular dependencies during validation pass", () => {
    const invalidIR = {
      name: "Cycle Test",
      triggers: [{ event: "push" as const }],
      jobs: [
        { id: "job-a", runsOn: "ubuntu-latest", needs: ["job-b"], steps: [{ kind: "run" as const, run: "echo A" }] },
        { id: "job-b", runsOn: "ubuntu-latest", needs: ["job-a"], steps: [{ kind: "run" as const, run: "echo B" }] }
      ]
    };

    const validation = validateWorkflowIR(invalidIR);
    expect(validation.valid).toBe(false);
    expect(validation.errors[0].message).toContain("Circular dependency");
  });
});
