import { execSync } from "node:child_process";
import { promises as fs } from "node:fs";
import path from "node:path";
import type { CreatePullRequestOptions, PullRequestResult } from "./types.js";

function parseRepoOwnerAndName(remoteUrl: string): { owner: string; repo: string } | null {
  const match = remoteUrl.match(/github\.com[/:]([^/]+)\/([^/.]+)/);
  if (!match) return null;
  return { owner: match[1], repo: match[2].replace(/\.git$/, "") };
}

export function generatePullRequestBody(options: CreatePullRequestOptions): string {
  const { state, ir, security, files } = options;

  const runtimes = state.runtime.map(r => `\`${r.name}\``).join(", ") || "None";
  const pms = state.packageManager.map(p => `\`${p.name}\``).join(", ") || "None";
  const frameworks = state.frameworks.map(f => `\`${f.name}\``).join(", ") || "None";
  const infra = state.infrastructure.map(i => `\`${i.name}\``).join(", ") || "None";

  const jobsList = ir.jobs.map(j => `- **${j.name ?? j.id}** (\`${j.runsOn}\`, ${j.steps.length} steps)`).join("\n");
  const filesList = files.map(f => `- \`${f.relativePath}\``).join("\n");

  const securityFeatures: string[] = [];
  if (security.dependabotYaml) securityFeatures.push("- ✅ **Dependabot**: Automated version & security updates");
  if (security.codeqlYaml) securityFeatures.push(`- ✅ **CodeQL SAST**: Multi-language vulnerability scanning (${security.policy.codeql.languages.join(", ")})`);
  if (security.securityWorkflowYaml) {
    const audits = security.policy.nativeAudits.map(a => a.tool).join(", ");
    securityFeatures.push(`- ✅ **Vulnerability Audits**: ${audits || "Container & Lockfile scans"}`);
  }

  return `## 🚀 Zero-Config CI/CD & Security Automation

This pull request was automatically generated by the **Zero-Config CI/CD Engine**. It equips this repository with a production-hardened GitHub Actions workflow pipeline and comprehensive security policies.

---

### 🔍 Discovered Architecture
| Component | Detected Technologies |
| :--- | :--- |
| **Runtimes** | ${runtimes} |
| **Package Managers** | ${pms} |
| **Frameworks** | ${frameworks} |
| **Infrastructure** | ${infra} |

---

### ⚡ Generated CI/CD Pipeline (\`.github/workflows/ci.yml\`)
${jobsList}

- **Parallel Execution Graph (DAG)**: Independent runtime/test jobs execute concurrently.
- **Dependency Caching**: Native cache keys configured for maximum build speed.
- **Production Hardening**: 15-minute job timeouts and automatic cancellation of superseded CI runs.

---

### 🛡️ Security Policies (Level: \`${security.policy.level.toUpperCase()}\`)
${securityFeatures.join("\n") || "- Basic security defaults applied."}

---

### 📁 Files Added
${filesList}

*Generated deterministically by Zero-Config CI/CD Engine.*
`;
}

export async function createGitHubPullRequest(
  options: CreatePullRequestOptions,
  token?: string
): Promise<PullRequestResult> {
  const { repoPath, remoteUrl, files, baseBranch = "main" } = options;
  const branchName = options.prBranch || `zcicd/setup-ci-${Date.now()}`;
  const authToken = token || process.env.GITHUB_TOKEN || process.env.GH_TOKEN;
  const parsed = parseRepoOwnerAndName(remoteUrl);

  try {
    // 1. Write files to working repository
    for (const file of files) {
      const fullPath = path.join(repoPath, file.relativePath);
      await fs.mkdir(path.dirname(fullPath), { recursive: true });
      await fs.writeFile(fullPath, file.content, "utf8");
    }

    // 2. Native Git operations (Branch & Commit)
    execSync(`git checkout -b "${branchName}"`, { cwd: repoPath, stdio: "pipe" });
    execSync(`git add .github/`, { cwd: repoPath, stdio: "pipe" });
    execSync(
      `git commit -m "ci: add zero-config CI/CD pipeline and security automation"`,
      { cwd: repoPath, stdio: "pipe" }
    );

    // 3. Push branch using native Git (leveraging Windows Git Credential Manager)
    let pushUrl = "origin";
    if (authToken && parsed) {
      pushUrl = `https://${authToken}@github.com/${parsed.owner}/${parsed.repo}.git`;
    }

    execSync(`git push -u "${pushUrl}" "${branchName}"`, { cwd: repoPath, stdio: "pipe" });

    const prTitle = "ci: add zero-config CI/CD pipeline & security automation";
    const prBody = generatePullRequestBody(options);

    // 4. Try creating PR via GitHub REST API if token is provided
    if (authToken && parsed) {
      try {
        const response = await fetch(`https://api.github.com/repos/${parsed.owner}/${parsed.repo}/pulls`, {
          method: "POST",
          headers: {
            Authorization: `Bearer ${authToken}`,
            Accept: "application/vnd.github+json",
            "Content-Type": "application/json",
            "User-Agent": "Zero-Config-CICD-Engine"
          },
          body: JSON.stringify({
            title: prTitle,
            body: prBody,
            head: branchName,
            base: baseBranch
          })
        });

        const data: any = await response.json();
        if (response.ok && data.html_url) {
          return {
            success: true,
            prUrl: data.html_url,
            branchName
          };
        }
      } catch {
        // Fall back to GitHub compare link
      }
    }

    // 5. Try creating PR via `gh` CLI if installed
    try {
      const prBodyPath = path.join(repoPath, ".pr-body.md");
      await fs.writeFile(prBodyPath, prBody, "utf8");

      const prOutput = execSync(
        `gh pr create --title "${prTitle}" --body-file "${prBodyPath}" --base "${baseBranch}" --head "${branchName}"`,
        { cwd: repoPath, encoding: "utf8", stdio: ["pipe", "pipe", "pipe"] }
      );

      try {
        await fs.unlink(prBodyPath);
      } catch {}

      const prUrlMatch = prOutput.match(/https:\/\/github\.com\/[^\s]+/);
      if (prUrlMatch) {
        return {
          success: true,
          prUrl: prUrlMatch[0].trim(),
          branchName
        };
      }
    } catch {
      // If gh is not installed, provide direct 1-click GitHub Pull Request link
    }

    // 6. Direct 1-Click Pull Request creation URL on GitHub
    const fallbackPrUrl = parsed
      ? `https://github.com/${parsed.owner}/${parsed.repo}/pull/new/${branchName}`
      : undefined;

    return {
      success: true,
      prUrl: fallbackPrUrl,
      branchName
    };
  } catch (err: any) {
    const message = err?.stderr?.toString() || err?.message || String(err);
    return {
      success: false,
      branchName,
      error: message
    };
  }
}
