import { stringify } from "yaml";
import type { SecurityPolicyIR } from "../types.js";

export function compileSecurityWorkflowYAML(policy: SecurityPolicyIR): string {
  const jobs: Record<string, unknown> = {};

  // 1. Dependency Audit Job
  if (policy.nativeAudits.length > 0) {
    const steps: Array<Record<string, unknown>> = [
      {
        name: "Checkout repository",
        uses: "actions/checkout@v4"
      }
    ];

    if (policy.secretScanning.enabled) {
      steps.unshift({
        name: "Harden GitHub Actions Runner",
        uses: "step-security/harden-runner@v2",
        with: {
          "egress-policy": "audit"
        }
      });
    }

    for (const audit of policy.nativeAudits) {
      const stepConfig: Record<string, unknown> = {
        name: `Run ${audit.tool}`,
        run: audit.command
      };

      // If policy is not blocking (Standard / Minimal), let CI report CVEs without blocking merge
      if (!audit.failOnError) {
        stepConfig["continue-on-error"] = true;
      }

      steps.push(stepConfig);
    }

    jobs["dependency-audit"] = {
      name: "Dependency Security Audit",
      "runs-on": "ubuntu-latest",
      "timeout-minutes": 15,
      steps
    };
  }

  // 2. Container Security Scan (Trivy)
  if (policy.containerScanning.enabled && policy.containerScanning.dockerfiles.length > 0) {
    const containerSteps: Array<Record<string, unknown>> = [
      {
        name: "Checkout repository",
        uses: "actions/checkout@v4"
      }
    ];

    if (policy.secretScanning.enabled) {
      containerSteps.unshift({
        name: "Harden GitHub Actions Runner",
        uses: "step-security/harden-runner@v2",
        with: {
          "egress-policy": "audit"
        }
      });
    }

    const firstDockerfile = policy.containerScanning.dockerfiles[0];
    containerSteps.push({
      name: "Build image for vulnerability scan",
      run: `docker build -t local-scan-target:latest -f "${firstDockerfile}" .`
    });

    const trivyWith: Record<string, unknown> = {
      "image-ref": "local-scan-target:latest",
      format: policy.containerScanning.uploadSarif ? "sarif" : "table",
      "ignore-unfixed": true,
      severity: policy.containerScanning.severityThreshold
    };

    if (policy.containerScanning.uploadSarif) {
      trivyWith.output = "trivy-results.sarif";
    }

    if (policy.enforcement.blockOnVulnerabilities) {
      trivyWith["exit-code"] = "1";
    }

    containerSteps.push({
      name: "Scan container image with Trivy",
      uses: "aquasecurity/trivy-action@master",
      with: trivyWith
    });

    if (policy.containerScanning.uploadSarif) {
      containerSteps.push({
        name: "Upload Trivy scan results to GitHub Security tab",
        uses: "github/codeql-action/upload-sarif@v3",
        with: {
          sarif_file: "trivy-results.sarif"
        }
      });
    }

    jobs["container-security"] = {
      name: "Container Vulnerability Scan (Trivy)",
      "runs-on": "ubuntu-latest",
      "timeout-minutes": 15,
      steps: containerSteps
    };
  }

  // 3. Secret Scanning (Gitleaks) for Strict mode
  if (policy.secretScanning.enabled) {
    jobs["secret-scan"] = {
      name: "Secret & Credential Scan (Gitleaks)",
      "runs-on": "ubuntu-latest",
      "timeout-minutes": 10,
      steps: [
        {
          name: "Checkout repository",
          uses: "actions/checkout@v4",
          with: { "fetch-depth": 0 }
        },
        {
          name: "Run Gitleaks",
          uses: "gitleaks/gitleaks-action@v2",
          env: {
            GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          }
        }
      ]
    };
  }

  if (Object.keys(jobs).length === 0) {
    return "";
  }

  const doc = {
    name: "Security & Vulnerability Scans",
    on: {
      push: { branches: ["main"] },
      pull_request: { branches: ["main"] }
    },
    permissions: {
      contents: "read",
      ...(policy.containerScanning.uploadSarif ? { "security-events": "write" } : {})
    },
    concurrency: {
      group: "${{ github.workflow }}-${{ github.ref }}",
      "cancel-in-progress": true
    },
    jobs
  };

  const yamlBody = stringify(doc, {
    indent: 2,
    lineWidth: 0,
    simpleKeys: true,
    aliasDuplicateObjects: false
  });

  return `# ==============================================================================
# Generated by Zero-Config CI/CD Engine
# Security & Vulnerability Scanning Workflow (Level: ${policy.level})
# ==============================================================================

${yamlBody}`;
}
