import { stringify } from "yaml";
import type { SecurityPolicyIR } from "../types.js";

export function compileCodeQLYAML(policy: SecurityPolicyIR): string {
  if (!policy.codeql.enabled || policy.codeql.languages.length === 0) {
    return "";
  }

  const queries = policy.level === "strict" ? "security-extended,security-and-quality" : "security-extended";

  const onObj: Record<string, unknown> = {
    push: { branches: ["main"] },
    pull_request: { branches: ["main"] }
  };

  if (policy.codeql.scheduleCron) {
    onObj.schedule = [{ cron: policy.codeql.scheduleCron }];
  }

  const doc = {
    name: "CodeQL Security Analysis",
    on: onObj,
    permissions: {
      contents: "read",
      "security-events": "write"
    },
    concurrency: {
      group: "${{ github.workflow }}-${{ github.ref }}",
      "cancel-in-progress": true
    },
    jobs: {
      analyze: {
        name: "CodeQL (${{ matrix.language }})",
        "runs-on": "ubuntu-latest",
        "timeout-minutes": 60,
        permissions: {
          contents: "read",
          "security-events": "write"
        },
        strategy: {
          "fail-fast": false,
          matrix: {
            language: policy.codeql.languages
          }
        },
        steps: [
          {
            name: "Checkout repository",
            uses: "actions/checkout@v4"
          },
          {
            name: "Initialize CodeQL",
            uses: "github/codeql-action/init@v3",
            with: {
              languages: "${{ matrix.language }}",
              queries
            }
          },
          {
            name: "Perform CodeQL Analysis",
            uses: "github/codeql-action/analyze@v3",
            with: {
              category: "/language:${{ matrix.language }}"
            }
          }
        ]
      }
    }
  };

  const yamlBody = stringify(doc, {
    indent: 2,
    lineWidth: 0,
    simpleKeys: true,
    aliasDuplicateObjects: false
  });

  return `# ==============================================================================
# Generated by Zero-Config CI/CD Engine
# GitHub CodeQL SAST Analysis Workflow (Level: ${policy.level})
# ==============================================================================

${yamlBody}`;
}
